### ISSUE TITLE
Vigenere module is broken

### ISSUE THREAD

**Issue by faneca** [fabd/kanji-koohii#93]
I tried cloning the repo and running a simple `autopwn` on some samples. Everytime I get this:
```
(...)
Running module: vigenere
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/ishell/console.py", line 102, in loop
    self.walk_and_run(input_)
  File "build/bdist.linux-x86_64/egg/ishell/console.py", line 69, in walk_and_run
    self.walk(command, 0, run=True, full_line=command)
  File "build/bdist.linux-x86_64/egg/ishell/console.py", line 54, in walk
    return cmd.complete(line_commands[1:], buf, state, run, full_line)
  File "build/bdist.linux-x86_64/egg/ishell/command.py", line 69, in complete
    return self.run(full_line.rstrip())
  File "featherduster.py", line 236, in run
    print feathermodules.module_list[attack]['attack_function'](feathermodules.samples)
  File "/home/roman/bin/packages/re/featherduster/feathermodules/classical/vigenere.py", line 16, in break_vigenere
    coefficient_word_count=float(options['coefficient_word_count']))
  File "/home/roman/bin/packages/re/featherduster/cryptanalib/classical.py", line 325, in break_vigenere
    key_lengths = evaluate_vigenere_key_length(ciphertext, scan_range)[:num_key_lengths]
  File "/home/roman/bin/packages/re/featherduster/cryptanalib/classical.py", line 237, in evaluate_vigenere_key_length
    key_length_best_guesses = map(list, zip(*ioc_best_guesses))[0]
IndexError: list index out of range
```

**Comment by fabd** [comment]
Hi faneca. I don't know what autopwn is. Can you follow the install instructions in Open Source: First Time Setup, and see if that works?

If you're trying to test the security of the site or run some kind of test suite, I can't help you with configuring them.

Most importantly if there is a security hole somewhere email me ;)

**Comment by fabd** [comment]
Ok I'm back. I should be available most of the day , early evening EU time so a good 8-10 hours from now.

I briefly Google `autopwn`. If it is a kind of tool that tests all kind of http get / post hacks for a website, than I assume it needs to run against the virtual host that you have setup. The error you post seems to be a problem with the script itself, which I can't do anything about.

**Comment by faneca** [comment]
Oh, sh*t, I cross posted, sorry! :-$$$
This was intended for a totally different repository. I can't barely understand how I messed up so badly. I'm really sorry.
orz
